### ISSUE TITLE
Issue with Including Tabs in current App

### ISSUE THREAD

**Issue by mastarenee** [zyra/ionic2-super-tabs-example#10]
After I insert the folllowing into my app.module.ts:

import { SuperTabsModule } from 'ionic2-super-tabs';
imports: [
    ....
    SuperTabsModule.forRoot()
  ]

I get the following error message:

Cannot find module 'ionic-angular/navigation/navigation-container'.

**Comment by ihadeed** [comment]
Make surw you're using ionic 3.5
