### ISSUE TITLE
rendering fail 

### ISSUE THREAD

**Issue by giscafer** [zyra/ionic2-super-tabs-example#11]
![qq 20170712141040](https://user-images.githubusercontent.com/8676711/28104093-ee5f3e40-670b-11e7-9956-9a9dede16197.png)

![qq 20170712141159](https://user-images.githubusercontent.com/8676711/28104126-18df1a50-670c-11e7-8a1b-dde0ae26575d.png)

**Comment by ihadeed** [comment]
Are you using `@ionic/app-scripts@2.0.0` ? if so, please update to `@ionic/app-scripts@2.0.1`

**Comment by giscafer** [comment]
now is work fine use `@ionic/app-scripts@2.0.1`
