### ISSUE TITLE
====>  HOW TO RUN THE EXAMPLE <====  click here

### ISSUE THREAD

**Issue by RaphaelBadia** [zyra/ionic2-super-tabs-example#17]
The submodule thing is broken.
**If you're lazy**, you can clone my workaround [here](https://github.com/RaphaelBadia/ionic2-super-tabs-example/)

or: 
1. run `npm i --save ionic2-super-tabs`
2. open app.modules.ts and replace line 6 with line 7
3. open shared.modules.ts and replace line 2 with line 3
4. open home.ts. remove line 5 and 6 and write `import {SuperTabsController, SuperTabs} from "ionic2-super-tabs";` at line 4

see https://github.com/zyra/ionic2-super-tabs-example/pull/16/files

**Comment by ihadeed** [comment]
What's wrong with the sub modules?

**Comment by ihadeed** [comment]
Just tested it out and it seems to be working fine.

Try editing `.gitmodules` and replace the value for `url` there. Use `https` instead of `ssh`. 

So basically replace this: `url = git@github.com:zyra/ionic2-super-tabs` with `url = https://github.com/zyra/ionic2-super-tabs`

**Comment by RaphaelBadia** [comment]
> So basically replace this: url = git@github.com:zyra/ionic2-super-tabs with url = https://github.com/zyra/ionic2-super-tabs

Thanks, maybe you should update the .gitmodules, because ssh is not setup on everyone's machine, while https works everywhere ( #13 , #15 )

**Comment by ihadeed** [comment]
Ok I'll update it.
