### ISSUE TITLE
Typescript Error Cannot find module '../ionic2-super-tabs/src'.

### ISSUE THREAD

**Issue by wilson0506** [zyra/ionic2-super-tabs-example#19]
typescript: src/pages/home/home.ts, line: 6 
            Cannot find module '../../ionic2-super-tabs/src/components/super-tab

**Comment by ihadeed** [comment]
Need to run `git submodule init && git submodule update`

**Comment by circuitry2** [comment]
I am seeing the same error after running git submodule update
