### ISSUE TITLE
git submodule update Error... 

### ISSUE THREAD

**Issue by mmcsacc** [zyra/ionic2-super-tabs-example#22]
I did: 
-> git clone https://github.com/zyra/ionic2-super-tabs-example
-> cd ionic2-super-tabs-example
-> git submodule init

And then,

->  git submodule update
And got this error
`
Cloning into '/Users/USER_NAME/Documents/ionicFun/ionic2-super-tabs-example/src/ionic2-super-tabs'...
error: no such remote ref bc9fd8dc35db502b2f47aeb103c061ed16807a49
Fetched in submodule path 'src/ionic2-super-tabs', but it did not contain bc9fd8dc35db502b2f47aeb103c061ed16807a49. Direct fetching of that commit failed.
`

**Comment by dcaillon** [comment]
Hi, I 've got the same type of error:
-> git submodule update
error: no such remote ref 5f1ace26cd3e89c2f9250502894d173e3c3abb78
Fetched in submodule path 'src/ionic2-super-tabs', but it did not contain 5f1ace26cd3e89c2f9250502894d173e3c3abb78. Direct fetching of that commit failed.

**Comment by ihadeed** [comment]
```
rm -rf src/ionic2-super-tabs
git clone https://github.com/zyra/ionic2-super-tabs src/ionic2-super-tabs
```
