### ISSUE TITLE
tab underline is in wrong position in landscape view

### ISSUE THREAD

**Issue by tezcane** [zyra/ionic2-super-tabs-example#5]
In v2.5.2 (and all previous versions) when you go from portrait to landscape mode, the underline under the right tab is in the wrong position.  See attached screenshot, the blue underline needs to be directly under the right tab but it is offset towards the left.
![capture](https://cloud.githubusercontent.com/assets/17792056/26074875/3ed64d7c-3968-11e7-832b-4e291edf9d46.PNG)

**Comment by ihadeed** [comment]
Closing this, I will respond to the issue opened in the main repo once this is fixed.
