### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by ish3lan** [zyra/ionic2-super-tabs-example#6]
```
Uncaught TypeError: Cannot read property 'nativeElement' of undefined
    at http://localhost:8100/build/main.js:74933:39
    at Array.forEach (native)
    at QueryList.forEach (http://localhost:8100/build/main.js:6031:65)
    at SuperTabsToolbar.indexSegmentButtonWidths (http://localhost:8100/build/main.js:74932:29)
    at http://localhost:8100/build/main.js:74879:23
```

**Comment by piotrowski** [comment]
Another report: https://forum.ionicframework.com/t/ionic2-super-tabs-example/90793

**Comment by piotrowski** [comment]
You should post your `ionic info` output for context.

**Comment by jcezarms** [comment]
I'm also going through this issue. In

**Comment by jcezarms** [comment]
I was also going through this exact same issue, running Ionic 3.1.2 in a hybrid application of mine. The thing is I just blindly set a `super-tabs` element with all the configurations I found at this repo's home page.

Later on I found that what was causing this for me was the `scrollTabs` input. If you've directly cloned this repo (or just went blind-coding like I did) and ran through this, **maybe** changing:
```
<super-tabs id="mainTabs"  [config]="{ sideMenu: 'left' }" scrollTabs toolbarColor="light" toolbarBackground="dark" indicatorColor="yellow" badgeColor="yellow" (tabSelect)="onTabSelect($event)">
```
into:
```
<super-tabs id="mainTabs"  [config]="{ sideMenu: 'left' }" toolbarColor="light" toolbarBackground="dark" indicatorColor="yellow" badgeColor="yellow" (tabSelect)="onTabSelect($event)">
```
at [src/pages/home/home.html](https://github.com/zyra/ionic2-super-tabs-example/blob/d257607f07ceb7bf804e4f498ce4ccf8a790a049/src/pages/home/home.html#L10) can solve your problem.

I only spent a few moments looking into this for component testing purposes, so I lack the knowledge to point why is this error ocurring or if the fix I'm proposing is the best one, but I hope it helps for the moment.

**Comment by ihadeed** [comment]
Please track the status of this issue here: https://github.com/zyra/ionic2-super-tabs/issues/49

A fix should be available tonight.

**Comment by ish3lan** [comment]
@ihadeed the example is still not working,pleaes reopen:
<img width="867" alt="screen shot 2017-05-19 at 2 50 12 pm" src="https://cloud.githubusercontent.com/assets/7420284/26246594/a72a35fe-3ca2-11e7-9e9d-156b2e2e72a9.png">


ionic info:
Your system information:

Cordova CLI: 7.0.1 
Ionic Framework Version: 3.2.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.10.3
Xcode version: Xcode 8.3.2 Build version 8E2002

**Comment by ihadeed** [comment]
@ish3lan this is a different issue..

Please read the new README in this repo.

Make sure you pull latest changes, then run the following commands:
```
git submodule init
git submodule update
npm install
```

**Comment by ish3lan** [comment]
thank you @ihadeed ,
following your comments, the app works perfectly on a real device

**Comment by orengbasha** [comment]
hi iam using super tab i facing problem toolbarcolor i given dark but if select the tab button how to change color red can you please help me in tabs it is possible to change active tab color but super tabs how please help me thanks you
