### ISSUE TITLE
What about Ionic 1

### ISSUE THREAD

**Issue by Pramodaexonic** [zyra/ionic2-super-tabs-example#9]
if want to implement this in old projects, of ionic 1 ?

**Comment by ihadeed** [comment]
I don't plan on creating a a version of this component for ionic 1

**Comment by Pramodaexonic** [comment]
Ok Fine. Do we have any other ref. to achieve this for ionic 1 project

**Comment by ihadeed** [comment]
@Pramodaexonic 

Sorry I'm not sure how to do that on Ionic 1. I think I saw a module in the Ionic market earlier.
